import type { Metadata } from 'next'
import { Header } from '@/components/Header'
import { MainContent } from '@/components/MainContent'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={` dark antialiased bg-background text-foreground flex size-full flex-col items-center justify-center`}
      >
        <MainContent header={<Header />}>{children}</MainContent>
      </body>
    </html>
  )
}
