import type { Metadata } from 'next'
import { Header } from '@/components/Header'
import { MainContent } from '@/components/MainContent'
import { Toaster } from '@/components/ui/toaster'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className="antialiased  min-h-svh flex flex-col"
        >
          <MainContent header={<Header />}>
            {children}
          </MainContent>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
