name: hackathon

services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/home/node/app
      - ./frontend/node_modules:/home/node/app/node_modules
    ports:
      - '3000:3000'
    networks:
        - hackathon

  backend:
    depends_on:
      - pg
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/node/app
      - ./backend/node_modules:/home/node/app/node_modules
    ports:
      - '8080:8080'
    networks:
        - hackathon

  pg:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hackathon
      - TZ=America/Sao_Paulo
    volumes:
      - hackathon:/var/lib/postgresql/data
    networks:
      - hackathon
volumes:
  hackathon:
    driver: local

networks:
  hackathon:
    driver: bridge
